# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

name: run-check

jobs:
  run-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-20.04,   r: '4.2'}
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ${{ github.workspace }}/R

    steps:
      - uses: actions/checkout@v3.5.2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::ggplot2
            any::dplyr
            any::tidyr

      - name: Run tests
        run: |
          sink("test.out")
          cat("running tutorial codes....")
          source("tutorial.R",echo=TRUE)
          cat("running munging codes....")
          source("munging.R",echo=TRUE)
          cat("running viz codes....")
          source("viz.R",echo=TRUE)
          sink()
        shell: Rscript {0}
      
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: install-test-${{ matrix.config.os }}-${{ matrix.config.r }}
          path: ${{ github.workspace }}/test.out
